#pragma once

enum OrderCallBackTypes {
  UNKNOWN,
  ORDER_ACCEPT,
  ORDER_ACCEPT_STOP,
  ORDER_TRIGGER_STOP,
  ORDER_REJECT,
  ORDER_FILL,
  ORDER_CANCEL,
  ORDER_CANCEL_STOP,
  ORDER_CANCEL_REJECT
};

enum OrderFillFlags {
  NEITHER_FILLED,
  INBOUND_FILLED,
  MATCHED_FILLED,
  BOTH_FILLED
};