// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file OrderMassStatusRequestTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#include "OrderMassStatusRequestTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "OrderMassStatusRequest.hpp"

#include "Header.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace DistributedStockExchange_OrderMassStatusRequest {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_OrderMassStatusRequest_type_identifier(
        TypeIdentifierPair& type_ids_OrderMassStatusRequest)
{

    ReturnCode_t return_code_OrderMassStatusRequest {eprosima::fastdds::dds::RETCODE_OK};
    return_code_OrderMassStatusRequest =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "DistributedStockExchange_OrderMassStatusRequest::OrderMassStatusRequest", type_ids_OrderMassStatusRequest);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_OrderMassStatusRequest)
    {
        StructTypeFlag struct_flags_OrderMassStatusRequest = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_OrderMassStatusRequest = "DistributedStockExchange_OrderMassStatusRequest::OrderMassStatusRequest";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_OrderMassStatusRequest;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_OrderMassStatusRequest;
        CompleteTypeDetail detail_OrderMassStatusRequest = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_OrderMassStatusRequest, ann_custom_OrderMassStatusRequest, type_name_OrderMassStatusRequest.to_string());
        CompleteStructHeader header_OrderMassStatusRequest;
        header_OrderMassStatusRequest = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_OrderMassStatusRequest);
        CompleteStructMemberSeq member_seq_OrderMassStatusRequest;
        {
            TypeIdentifierPair type_ids_Source;
            ReturnCode_t return_code_Source {eprosima::fastdds::dds::RETCODE_OK};
            return_code_Source =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_Source);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_Source)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_Source))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_Source = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_Source = 0x00000000;
            bool common_Source_ec {false};
            CommonStructMember common_Source {TypeObjectUtils::build_common_struct_member(member_id_Source, member_flags_Source, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_Source, common_Source_ec))};
            if (!common_Source_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure Source member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_Source = "Source";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_Source;
            ann_custom_OrderMassStatusRequest.reset();
            CompleteMemberDetail detail_Source = TypeObjectUtils::build_complete_member_detail(name_Source, member_ann_builtin_Source, ann_custom_OrderMassStatusRequest);
            CompleteStructMember member_Source = TypeObjectUtils::build_complete_struct_member(common_Source, detail_Source);
            TypeObjectUtils::add_complete_struct_member(member_seq_OrderMassStatusRequest, member_Source);
        }
        {
            TypeIdentifierPair type_ids_Destination;
            ReturnCode_t return_code_Destination {eprosima::fastdds::dds::RETCODE_OK};
            return_code_Destination =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_Destination);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_Destination)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_Destination))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_Destination = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_Destination = 0x00000001;
            bool common_Destination_ec {false};
            CommonStructMember common_Destination {TypeObjectUtils::build_common_struct_member(member_id_Destination, member_flags_Destination, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_Destination, common_Destination_ec))};
            if (!common_Destination_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure Destination member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_Destination = "Destination";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_Destination;
            ann_custom_OrderMassStatusRequest.reset();
            CompleteMemberDetail detail_Destination = TypeObjectUtils::build_complete_member_detail(name_Destination, member_ann_builtin_Destination, ann_custom_OrderMassStatusRequest);
            CompleteStructMember member_Destination = TypeObjectUtils::build_complete_struct_member(common_Destination, detail_Destination);
            TypeObjectUtils::add_complete_struct_member(member_seq_OrderMassStatusRequest, member_Destination);
        }
        {
            TypeIdentifierPair type_ids_SourceUser;
            ReturnCode_t return_code_SourceUser {eprosima::fastdds::dds::RETCODE_OK};
            return_code_SourceUser =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_SourceUser);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_SourceUser)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_SourceUser))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_SourceUser = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_SourceUser = 0x00000002;
            bool common_SourceUser_ec {false};
            CommonStructMember common_SourceUser {TypeObjectUtils::build_common_struct_member(member_id_SourceUser, member_flags_SourceUser, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_SourceUser, common_SourceUser_ec))};
            if (!common_SourceUser_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure SourceUser member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_SourceUser = "SourceUser";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_SourceUser;
            ann_custom_OrderMassStatusRequest.reset();
            CompleteMemberDetail detail_SourceUser = TypeObjectUtils::build_complete_member_detail(name_SourceUser, member_ann_builtin_SourceUser, ann_custom_OrderMassStatusRequest);
            CompleteStructMember member_SourceUser = TypeObjectUtils::build_complete_struct_member(common_SourceUser, detail_SourceUser);
            TypeObjectUtils::add_complete_struct_member(member_seq_OrderMassStatusRequest, member_SourceUser);
        }
        {
            TypeIdentifierPair type_ids_DestinationUser;
            ReturnCode_t return_code_DestinationUser {eprosima::fastdds::dds::RETCODE_OK};
            return_code_DestinationUser =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_DestinationUser);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_DestinationUser)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_DestinationUser))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_DestinationUser = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_DestinationUser = 0x00000003;
            bool common_DestinationUser_ec {false};
            CommonStructMember common_DestinationUser {TypeObjectUtils::build_common_struct_member(member_id_DestinationUser, member_flags_DestinationUser, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_DestinationUser, common_DestinationUser_ec))};
            if (!common_DestinationUser_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure DestinationUser member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_DestinationUser = "DestinationUser";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_DestinationUser;
            ann_custom_OrderMassStatusRequest.reset();
            CompleteMemberDetail detail_DestinationUser = TypeObjectUtils::build_complete_member_detail(name_DestinationUser, member_ann_builtin_DestinationUser, ann_custom_OrderMassStatusRequest);
            CompleteStructMember member_DestinationUser = TypeObjectUtils::build_complete_struct_member(common_DestinationUser, detail_DestinationUser);
            TypeObjectUtils::add_complete_struct_member(member_seq_OrderMassStatusRequest, member_DestinationUser);
        }
        {
            TypeIdentifierPair type_ids_fix_header;
            ReturnCode_t return_code_fix_header {eprosima::fastdds::dds::RETCODE_OK};
            return_code_fix_header =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "DistributedStockExchange::Header", type_ids_fix_header);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_fix_header)
            {
                DistributedStockExchange::register_Header_type_identifier(type_ids_fix_header);
            }
            StructMemberFlag member_flags_fix_header = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_fix_header = 0x00000004;
            bool common_fix_header_ec {false};
            CommonStructMember common_fix_header {TypeObjectUtils::build_common_struct_member(member_id_fix_header, member_flags_fix_header, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_fix_header, common_fix_header_ec))};
            if (!common_fix_header_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure fix_header member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_fix_header = "fix_header";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_fix_header;
            ann_custom_OrderMassStatusRequest.reset();
            CompleteMemberDetail detail_fix_header = TypeObjectUtils::build_complete_member_detail(name_fix_header, member_ann_builtin_fix_header, ann_custom_OrderMassStatusRequest);
            CompleteStructMember member_fix_header = TypeObjectUtils::build_complete_struct_member(common_fix_header, detail_fix_header);
            TypeObjectUtils::add_complete_struct_member(member_seq_OrderMassStatusRequest, member_fix_header);
        }
        {
            TypeIdentifierPair type_ids_MassStatusReqID;
            ReturnCode_t return_code_MassStatusReqID {eprosima::fastdds::dds::RETCODE_OK};
            return_code_MassStatusReqID =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_MassStatusReqID);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_MassStatusReqID)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_MassStatusReqID))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_MassStatusReqID = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_MassStatusReqID = 0x00000005;
            bool common_MassStatusReqID_ec {false};
            CommonStructMember common_MassStatusReqID {TypeObjectUtils::build_common_struct_member(member_id_MassStatusReqID, member_flags_MassStatusReqID, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_MassStatusReqID, common_MassStatusReqID_ec))};
            if (!common_MassStatusReqID_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure MassStatusReqID member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_MassStatusReqID = "MassStatusReqID";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_MassStatusReqID;
            ann_custom_OrderMassStatusRequest.reset();
            CompleteMemberDetail detail_MassStatusReqID = TypeObjectUtils::build_complete_member_detail(name_MassStatusReqID, member_ann_builtin_MassStatusReqID, ann_custom_OrderMassStatusRequest);
            CompleteStructMember member_MassStatusReqID = TypeObjectUtils::build_complete_struct_member(common_MassStatusReqID, detail_MassStatusReqID);
            TypeObjectUtils::add_complete_struct_member(member_seq_OrderMassStatusRequest, member_MassStatusReqID);
        }
        {
            TypeIdentifierPair type_ids_MassStatusReqType;
            ReturnCode_t return_code_MassStatusReqType {eprosima::fastdds::dds::RETCODE_OK};
            return_code_MassStatusReqType =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_MassStatusReqType);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_MassStatusReqType)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "MassStatusReqType Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_MassStatusReqType = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_MassStatusReqType = 0x00000006;
            bool common_MassStatusReqType_ec {false};
            CommonStructMember common_MassStatusReqType {TypeObjectUtils::build_common_struct_member(member_id_MassStatusReqType, member_flags_MassStatusReqType, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_MassStatusReqType, common_MassStatusReqType_ec))};
            if (!common_MassStatusReqType_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure MassStatusReqType member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_MassStatusReqType = "MassStatusReqType";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_MassStatusReqType;
            ann_custom_OrderMassStatusRequest.reset();
            CompleteMemberDetail detail_MassStatusReqType = TypeObjectUtils::build_complete_member_detail(name_MassStatusReqType, member_ann_builtin_MassStatusReqType, ann_custom_OrderMassStatusRequest);
            CompleteStructMember member_MassStatusReqType = TypeObjectUtils::build_complete_struct_member(common_MassStatusReqType, detail_MassStatusReqType);
            TypeObjectUtils::add_complete_struct_member(member_seq_OrderMassStatusRequest, member_MassStatusReqType);
        }
        {
            TypeIdentifierPair type_ids_Symbol;
            ReturnCode_t return_code_Symbol {eprosima::fastdds::dds::RETCODE_OK};
            return_code_Symbol =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_Symbol);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_Symbol)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_Symbol))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_Symbol = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_Symbol = 0x00000007;
            bool common_Symbol_ec {false};
            CommonStructMember common_Symbol {TypeObjectUtils::build_common_struct_member(member_id_Symbol, member_flags_Symbol, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_Symbol, common_Symbol_ec))};
            if (!common_Symbol_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure Symbol member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_Symbol = "Symbol";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_Symbol;
            ann_custom_OrderMassStatusRequest.reset();
            CompleteMemberDetail detail_Symbol = TypeObjectUtils::build_complete_member_detail(name_Symbol, member_ann_builtin_Symbol, ann_custom_OrderMassStatusRequest);
            CompleteStructMember member_Symbol = TypeObjectUtils::build_complete_struct_member(common_Symbol, detail_Symbol);
            TypeObjectUtils::add_complete_struct_member(member_seq_OrderMassStatusRequest, member_Symbol);
        }
        {
            TypeIdentifierPair type_ids_SecurityExchange;
            ReturnCode_t return_code_SecurityExchange {eprosima::fastdds::dds::RETCODE_OK};
            return_code_SecurityExchange =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_SecurityExchange);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_SecurityExchange)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_SecurityExchange))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_SecurityExchange = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_SecurityExchange = 0x00000008;
            bool common_SecurityExchange_ec {false};
            CommonStructMember common_SecurityExchange {TypeObjectUtils::build_common_struct_member(member_id_SecurityExchange, member_flags_SecurityExchange, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_SecurityExchange, common_SecurityExchange_ec))};
            if (!common_SecurityExchange_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure SecurityExchange member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_SecurityExchange = "SecurityExchange";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_SecurityExchange;
            ann_custom_OrderMassStatusRequest.reset();
            CompleteMemberDetail detail_SecurityExchange = TypeObjectUtils::build_complete_member_detail(name_SecurityExchange, member_ann_builtin_SecurityExchange, ann_custom_OrderMassStatusRequest);
            CompleteStructMember member_SecurityExchange = TypeObjectUtils::build_complete_struct_member(common_SecurityExchange, detail_SecurityExchange);
            TypeObjectUtils::add_complete_struct_member(member_seq_OrderMassStatusRequest, member_SecurityExchange);
        }
        CompleteStructType struct_type_OrderMassStatusRequest = TypeObjectUtils::build_complete_struct_type(struct_flags_OrderMassStatusRequest, header_OrderMassStatusRequest, member_seq_OrderMassStatusRequest);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_OrderMassStatusRequest, type_name_OrderMassStatusRequest.to_string(), type_ids_OrderMassStatusRequest))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "DistributedStockExchange_OrderMassStatusRequest::OrderMassStatusRequest already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace DistributedStockExchange_OrderMassStatusRequest

