#include "Header.idl"

module DistributedStockExchange_OrderMassCancelReport
{

	
	struct OrderMassCancelReport
	{
		string Source;
     		string Destination;
    		string SourceUser;
    		string DestinationUser;


		DistributedStockExchange::Header fix_header;

		string OrderID;
		char MassCancelRequestType;
		char MassCancelResponse;
		string Symbol;
		string SecurityExchange;
		unsigned long long TransactTime;
		string Text;
	};
};
