// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file HeartbeatTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen.
 */

#include "HeartbeatTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "Heartbeat.hpp"

#include "Header.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace Heartbeat {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Heartbeat_type_identifier(
        TypeIdentifierPair& type_ids_Heartbeat)
{

    ReturnCode_t return_code_Heartbeat {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Heartbeat =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "Heartbeat::Heartbeat", type_ids_Heartbeat);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Heartbeat)
    {
        StructTypeFlag struct_flags_Heartbeat = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_Heartbeat = "Heartbeat::Heartbeat";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Heartbeat;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Heartbeat;
        CompleteTypeDetail detail_Heartbeat = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Heartbeat, ann_custom_Heartbeat, type_name_Heartbeat.to_string());
        CompleteStructHeader header_Heartbeat;
        header_Heartbeat = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Heartbeat);
        CompleteStructMemberSeq member_seq_Heartbeat;
        {
            TypeIdentifierPair type_ids_header;
            ReturnCode_t return_code_header {eprosima::fastdds::dds::RETCODE_OK};
            return_code_header =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "Header", type_ids_header);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_header)
            {
            ::register_Header_type_identifier(type_ids_header);
            }
            StructMemberFlag member_flags_header = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_header = 0x00000000;
            bool common_header_ec {false};
            CommonStructMember common_header {TypeObjectUtils::build_common_struct_member(member_id_header, member_flags_header, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_header, common_header_ec))};
            if (!common_header_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure header member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_header = "header";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_header;
            ann_custom_Heartbeat.reset();
            CompleteMemberDetail detail_header = TypeObjectUtils::build_complete_member_detail(name_header, member_ann_builtin_header, ann_custom_Heartbeat);
            CompleteStructMember member_header = TypeObjectUtils::build_complete_struct_member(common_header, detail_header);
            TypeObjectUtils::add_complete_struct_member(member_seq_Heartbeat, member_header);
        }
        CompleteStructType struct_type_Heartbeat = TypeObjectUtils::build_complete_struct_type(struct_flags_Heartbeat, header_Heartbeat, member_seq_Heartbeat);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Heartbeat, type_name_Heartbeat.to_string(), type_ids_Heartbeat))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "Heartbeat::Heartbeat already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace Heartbeat

