// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file LogonTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen.
 */

#include "LogonTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "Logon.hpp"

#include "Header.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace Logon {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Logon_type_identifier(
        TypeIdentifierPair& type_ids_Logon)
{

    ReturnCode_t return_code_Logon {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Logon =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "Logon::Logon", type_ids_Logon);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Logon)
    {
        StructTypeFlag struct_flags_Logon = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_Logon = "Logon::Logon";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Logon;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Logon;
        CompleteTypeDetail detail_Logon = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Logon, ann_custom_Logon, type_name_Logon.to_string());
        CompleteStructHeader header_Logon;
        header_Logon = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Logon);
        CompleteStructMemberSeq member_seq_Logon;
        {
            TypeIdentifierPair type_ids_header;
            ReturnCode_t return_code_header {eprosima::fastdds::dds::RETCODE_OK};
            return_code_header =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "Header", type_ids_header);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_header)
            {
            ::register_Header_type_identifier(type_ids_header);
            }
            StructMemberFlag member_flags_header = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_header = 0x00000000;
            bool common_header_ec {false};
            CommonStructMember common_header {TypeObjectUtils::build_common_struct_member(member_id_header, member_flags_header, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_header, common_header_ec))};
            if (!common_header_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure header member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_header = "header";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_header;
            ann_custom_Logon.reset();
            CompleteMemberDetail detail_header = TypeObjectUtils::build_complete_member_detail(name_header, member_ann_builtin_header, ann_custom_Logon);
            CompleteStructMember member_header = TypeObjectUtils::build_complete_struct_member(common_header, detail_header);
            TypeObjectUtils::add_complete_struct_member(member_seq_Logon, member_header);
        }
        {
            TypeIdentifierPair type_ids_EncryptMethod;
            ReturnCode_t return_code_EncryptMethod {eprosima::fastdds::dds::RETCODE_OK};
            return_code_EncryptMethod =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_EncryptMethod);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_EncryptMethod)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "EncryptMethod Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_EncryptMethod = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_EncryptMethod = 0x00000001;
            bool common_EncryptMethod_ec {false};
            CommonStructMember common_EncryptMethod {TypeObjectUtils::build_common_struct_member(member_id_EncryptMethod, member_flags_EncryptMethod, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_EncryptMethod, common_EncryptMethod_ec))};
            if (!common_EncryptMethod_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure EncryptMethod member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_EncryptMethod = "EncryptMethod";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_EncryptMethod;
            ann_custom_Logon.reset();
            CompleteMemberDetail detail_EncryptMethod = TypeObjectUtils::build_complete_member_detail(name_EncryptMethod, member_ann_builtin_EncryptMethod, ann_custom_Logon);
            CompleteStructMember member_EncryptMethod = TypeObjectUtils::build_complete_struct_member(common_EncryptMethod, detail_EncryptMethod);
            TypeObjectUtils::add_complete_struct_member(member_seq_Logon, member_EncryptMethod);
        }
        {
            TypeIdentifierPair type_ids_HeartBtInt;
            ReturnCode_t return_code_HeartBtInt {eprosima::fastdds::dds::RETCODE_OK};
            return_code_HeartBtInt =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_HeartBtInt);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_HeartBtInt)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "HeartBtInt Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_HeartBtInt = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_HeartBtInt = 0x00000002;
            bool common_HeartBtInt_ec {false};
            CommonStructMember common_HeartBtInt {TypeObjectUtils::build_common_struct_member(member_id_HeartBtInt, member_flags_HeartBtInt, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_HeartBtInt, common_HeartBtInt_ec))};
            if (!common_HeartBtInt_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure HeartBtInt member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_HeartBtInt = "HeartBtInt";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_HeartBtInt;
            ann_custom_Logon.reset();
            CompleteMemberDetail detail_HeartBtInt = TypeObjectUtils::build_complete_member_detail(name_HeartBtInt, member_ann_builtin_HeartBtInt, ann_custom_Logon);
            CompleteStructMember member_HeartBtInt = TypeObjectUtils::build_complete_struct_member(common_HeartBtInt, detail_HeartBtInt);
            TypeObjectUtils::add_complete_struct_member(member_seq_Logon, member_HeartBtInt);
        }
        {
            TypeIdentifierPair type_ids_RawData;
            ReturnCode_t return_code_RawData {eprosima::fastdds::dds::RETCODE_OK};
            return_code_RawData =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_RawData);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_RawData)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_RawData))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_RawData = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_RawData = 0x00000003;
            bool common_RawData_ec {false};
            CommonStructMember common_RawData {TypeObjectUtils::build_common_struct_member(member_id_RawData, member_flags_RawData, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_RawData, common_RawData_ec))};
            if (!common_RawData_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure RawData member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_RawData = "RawData";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_RawData;
            ann_custom_Logon.reset();
            CompleteMemberDetail detail_RawData = TypeObjectUtils::build_complete_member_detail(name_RawData, member_ann_builtin_RawData, ann_custom_Logon);
            CompleteStructMember member_RawData = TypeObjectUtils::build_complete_struct_member(common_RawData, detail_RawData);
            TypeObjectUtils::add_complete_struct_member(member_seq_Logon, member_RawData);
        }
        {
            TypeIdentifierPair type_ids_Username;
            ReturnCode_t return_code_Username {eprosima::fastdds::dds::RETCODE_OK};
            return_code_Username =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_Username);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_Username)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_Username))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_Username = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_Username = 0x00000004;
            bool common_Username_ec {false};
            CommonStructMember common_Username {TypeObjectUtils::build_common_struct_member(member_id_Username, member_flags_Username, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_Username, common_Username_ec))};
            if (!common_Username_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure Username member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_Username = "Username";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_Username;
            ann_custom_Logon.reset();
            CompleteMemberDetail detail_Username = TypeObjectUtils::build_complete_member_detail(name_Username, member_ann_builtin_Username, ann_custom_Logon);
            CompleteStructMember member_Username = TypeObjectUtils::build_complete_struct_member(common_Username, detail_Username);
            TypeObjectUtils::add_complete_struct_member(member_seq_Logon, member_Username);
        }
        {
            TypeIdentifierPair type_ids_Password;
            ReturnCode_t return_code_Password {eprosima::fastdds::dds::RETCODE_OK};
            return_code_Password =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_Password);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_Password)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_Password))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_Password = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_Password = 0x00000005;
            bool common_Password_ec {false};
            CommonStructMember common_Password {TypeObjectUtils::build_common_struct_member(member_id_Password, member_flags_Password, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_Password, common_Password_ec))};
            if (!common_Password_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure Password member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_Password = "Password";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_Password;
            ann_custom_Logon.reset();
            CompleteMemberDetail detail_Password = TypeObjectUtils::build_complete_member_detail(name_Password, member_ann_builtin_Password, ann_custom_Logon);
            CompleteStructMember member_Password = TypeObjectUtils::build_complete_struct_member(common_Password, detail_Password);
            TypeObjectUtils::add_complete_struct_member(member_seq_Logon, member_Password);
        }
        CompleteStructType struct_type_Logon = TypeObjectUtils::build_complete_struct_type(struct_flags_Logon, header_Logon, member_seq_Logon);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Logon, type_name_Logon.to_string(), type_ids_Logon))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "Logon::Logon already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace Logon

