// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MarketDataIncrementalRefresh.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__MARKETDATAINCREMENTALREFRESH_MARKETDATAINCREMENTALREFRESH_HPP
#define FAST_DDS_GENERATED__MARKETDATAINCREMENTALREFRESH_MARKETDATAINCREMENTALREFRESH_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include "Header.hpp"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MARKETDATAINCREMENTALREFRESH_SOURCE)
#define MARKETDATAINCREMENTALREFRESH_DllAPI __declspec( dllexport )
#else
#define MARKETDATAINCREMENTALREFRESH_DllAPI __declspec( dllimport )
#endif // MARKETDATAINCREMENTALREFRESH_SOURCE
#else
#define MARKETDATAINCREMENTALREFRESH_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define MARKETDATAINCREMENTALREFRESH_DllAPI
#endif // _WIN32

namespace MarketDataIncrementalRefresh {

/*!
 * @brief This class represents the structure NoMDEntries defined by the user in the IDL file.
 * @ingroup MarketDataIncrementalRefresh
 */
class NoMDEntries
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport NoMDEntries()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~NoMDEntries()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object NoMDEntries that will be copied.
     */
    eProsima_user_DllExport NoMDEntries(
            const NoMDEntries& x)
    {
                    m_MDUpdateAction = x.m_MDUpdateAction;

                    m_MDEntryType = x.m_MDEntryType;

                    m_Symbol = x.m_Symbol;

                    m_SecurityExchange = x.m_SecurityExchange;

                    m_MDEntryPx = x.m_MDEntryPx;

                    m_MDEntrySize = x.m_MDEntrySize;

                    m_TimeInForce = x.m_TimeInForce;

                    m_ExecInst = x.m_ExecInst;

                    m_Text = x.m_Text;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object NoMDEntries that will be copied.
     */
    eProsima_user_DllExport NoMDEntries(
            NoMDEntries&& x) noexcept
    {
        m_MDUpdateAction = x.m_MDUpdateAction;
        m_MDEntryType = x.m_MDEntryType;
        m_Symbol = std::move(x.m_Symbol);
        m_SecurityExchange = std::move(x.m_SecurityExchange);
        m_MDEntryPx = x.m_MDEntryPx;
        m_MDEntrySize = x.m_MDEntrySize;
        m_TimeInForce = x.m_TimeInForce;
        m_ExecInst = std::move(x.m_ExecInst);
        m_Text = std::move(x.m_Text);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object NoMDEntries that will be copied.
     */
    eProsima_user_DllExport NoMDEntries& operator =(
            const NoMDEntries& x)
    {

                    m_MDUpdateAction = x.m_MDUpdateAction;

                    m_MDEntryType = x.m_MDEntryType;

                    m_Symbol = x.m_Symbol;

                    m_SecurityExchange = x.m_SecurityExchange;

                    m_MDEntryPx = x.m_MDEntryPx;

                    m_MDEntrySize = x.m_MDEntrySize;

                    m_TimeInForce = x.m_TimeInForce;

                    m_ExecInst = x.m_ExecInst;

                    m_Text = x.m_Text;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object NoMDEntries that will be copied.
     */
    eProsima_user_DllExport NoMDEntries& operator =(
            NoMDEntries&& x) noexcept
    {

        m_MDUpdateAction = x.m_MDUpdateAction;
        m_MDEntryType = x.m_MDEntryType;
        m_Symbol = std::move(x.m_Symbol);
        m_SecurityExchange = std::move(x.m_SecurityExchange);
        m_MDEntryPx = x.m_MDEntryPx;
        m_MDEntrySize = x.m_MDEntrySize;
        m_TimeInForce = x.m_TimeInForce;
        m_ExecInst = std::move(x.m_ExecInst);
        m_Text = std::move(x.m_Text);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x NoMDEntries object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const NoMDEntries& x) const
    {
        return (m_MDUpdateAction == x.m_MDUpdateAction &&
           m_MDEntryType == x.m_MDEntryType &&
           m_Symbol == x.m_Symbol &&
           m_SecurityExchange == x.m_SecurityExchange &&
           m_MDEntryPx == x.m_MDEntryPx &&
           m_MDEntrySize == x.m_MDEntrySize &&
           m_TimeInForce == x.m_TimeInForce &&
           m_ExecInst == x.m_ExecInst &&
           m_Text == x.m_Text);
    }

    /*!
     * @brief Comparison operator.
     * @param x NoMDEntries object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const NoMDEntries& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member MDUpdateAction
     * @param _MDUpdateAction New value for member MDUpdateAction
     */
    eProsima_user_DllExport void MDUpdateAction(
            char _MDUpdateAction)
    {
        m_MDUpdateAction = _MDUpdateAction;
    }

    /*!
     * @brief This function returns the value of member MDUpdateAction
     * @return Value of member MDUpdateAction
     */
    eProsima_user_DllExport char MDUpdateAction() const
    {
        return m_MDUpdateAction;
    }

    /*!
     * @brief This function returns a reference to member MDUpdateAction
     * @return Reference to member MDUpdateAction
     */
    eProsima_user_DllExport char& MDUpdateAction()
    {
        return m_MDUpdateAction;
    }


    /*!
     * @brief This function sets a value in member MDEntryType
     * @param _MDEntryType New value for member MDEntryType
     */
    eProsima_user_DllExport void MDEntryType(
            char _MDEntryType)
    {
        m_MDEntryType = _MDEntryType;
    }

    /*!
     * @brief This function returns the value of member MDEntryType
     * @return Value of member MDEntryType
     */
    eProsima_user_DllExport char MDEntryType() const
    {
        return m_MDEntryType;
    }

    /*!
     * @brief This function returns a reference to member MDEntryType
     * @return Reference to member MDEntryType
     */
    eProsima_user_DllExport char& MDEntryType()
    {
        return m_MDEntryType;
    }


    /*!
     * @brief This function copies the value in member Symbol
     * @param _Symbol New value to be copied in member Symbol
     */
    eProsima_user_DllExport void Symbol(
            const std::string& _Symbol)
    {
        m_Symbol = _Symbol;
    }

    /*!
     * @brief This function moves the value in member Symbol
     * @param _Symbol New value to be moved in member Symbol
     */
    eProsima_user_DllExport void Symbol(
            std::string&& _Symbol)
    {
        m_Symbol = std::move(_Symbol);
    }

    /*!
     * @brief This function returns a constant reference to member Symbol
     * @return Constant reference to member Symbol
     */
    eProsima_user_DllExport const std::string& Symbol() const
    {
        return m_Symbol;
    }

    /*!
     * @brief This function returns a reference to member Symbol
     * @return Reference to member Symbol
     */
    eProsima_user_DllExport std::string& Symbol()
    {
        return m_Symbol;
    }


    /*!
     * @brief This function copies the value in member SecurityExchange
     * @param _SecurityExchange New value to be copied in member SecurityExchange
     */
    eProsima_user_DllExport void SecurityExchange(
            const std::string& _SecurityExchange)
    {
        m_SecurityExchange = _SecurityExchange;
    }

    /*!
     * @brief This function moves the value in member SecurityExchange
     * @param _SecurityExchange New value to be moved in member SecurityExchange
     */
    eProsima_user_DllExport void SecurityExchange(
            std::string&& _SecurityExchange)
    {
        m_SecurityExchange = std::move(_SecurityExchange);
    }

    /*!
     * @brief This function returns a constant reference to member SecurityExchange
     * @return Constant reference to member SecurityExchange
     */
    eProsima_user_DllExport const std::string& SecurityExchange() const
    {
        return m_SecurityExchange;
    }

    /*!
     * @brief This function returns a reference to member SecurityExchange
     * @return Reference to member SecurityExchange
     */
    eProsima_user_DllExport std::string& SecurityExchange()
    {
        return m_SecurityExchange;
    }


    /*!
     * @brief This function sets a value in member MDEntryPx
     * @param _MDEntryPx New value for member MDEntryPx
     */
    eProsima_user_DllExport void MDEntryPx(
            float _MDEntryPx)
    {
        m_MDEntryPx = _MDEntryPx;
    }

    /*!
     * @brief This function returns the value of member MDEntryPx
     * @return Value of member MDEntryPx
     */
    eProsima_user_DllExport float MDEntryPx() const
    {
        return m_MDEntryPx;
    }

    /*!
     * @brief This function returns a reference to member MDEntryPx
     * @return Reference to member MDEntryPx
     */
    eProsima_user_DllExport float& MDEntryPx()
    {
        return m_MDEntryPx;
    }


    /*!
     * @brief This function sets a value in member MDEntrySize
     * @param _MDEntrySize New value for member MDEntrySize
     */
    eProsima_user_DllExport void MDEntrySize(
            int32_t _MDEntrySize)
    {
        m_MDEntrySize = _MDEntrySize;
    }

    /*!
     * @brief This function returns the value of member MDEntrySize
     * @return Value of member MDEntrySize
     */
    eProsima_user_DllExport int32_t MDEntrySize() const
    {
        return m_MDEntrySize;
    }

    /*!
     * @brief This function returns a reference to member MDEntrySize
     * @return Reference to member MDEntrySize
     */
    eProsima_user_DllExport int32_t& MDEntrySize()
    {
        return m_MDEntrySize;
    }


    /*!
     * @brief This function sets a value in member TimeInForce
     * @param _TimeInForce New value for member TimeInForce
     */
    eProsima_user_DllExport void TimeInForce(
            char _TimeInForce)
    {
        m_TimeInForce = _TimeInForce;
    }

    /*!
     * @brief This function returns the value of member TimeInForce
     * @return Value of member TimeInForce
     */
    eProsima_user_DllExport char TimeInForce() const
    {
        return m_TimeInForce;
    }

    /*!
     * @brief This function returns a reference to member TimeInForce
     * @return Reference to member TimeInForce
     */
    eProsima_user_DllExport char& TimeInForce()
    {
        return m_TimeInForce;
    }


    /*!
     * @brief This function copies the value in member ExecInst
     * @param _ExecInst New value to be copied in member ExecInst
     */
    eProsima_user_DllExport void ExecInst(
            const std::string& _ExecInst)
    {
        m_ExecInst = _ExecInst;
    }

    /*!
     * @brief This function moves the value in member ExecInst
     * @param _ExecInst New value to be moved in member ExecInst
     */
    eProsima_user_DllExport void ExecInst(
            std::string&& _ExecInst)
    {
        m_ExecInst = std::move(_ExecInst);
    }

    /*!
     * @brief This function returns a constant reference to member ExecInst
     * @return Constant reference to member ExecInst
     */
    eProsima_user_DllExport const std::string& ExecInst() const
    {
        return m_ExecInst;
    }

    /*!
     * @brief This function returns a reference to member ExecInst
     * @return Reference to member ExecInst
     */
    eProsima_user_DllExport std::string& ExecInst()
    {
        return m_ExecInst;
    }


    /*!
     * @brief This function copies the value in member Text
     * @param _Text New value to be copied in member Text
     */
    eProsima_user_DllExport void Text(
            const std::string& _Text)
    {
        m_Text = _Text;
    }

    /*!
     * @brief This function moves the value in member Text
     * @param _Text New value to be moved in member Text
     */
    eProsima_user_DllExport void Text(
            std::string&& _Text)
    {
        m_Text = std::move(_Text);
    }

    /*!
     * @brief This function returns a constant reference to member Text
     * @return Constant reference to member Text
     */
    eProsima_user_DllExport const std::string& Text() const
    {
        return m_Text;
    }

    /*!
     * @brief This function returns a reference to member Text
     * @return Reference to member Text
     */
    eProsima_user_DllExport std::string& Text()
    {
        return m_Text;
    }



private:

    char m_MDUpdateAction{0};
    char m_MDEntryType{0};
    std::string m_Symbol;
    std::string m_SecurityExchange;
    float m_MDEntryPx{0.0};
    int32_t m_MDEntrySize{0};
    char m_TimeInForce{0};
    std::string m_ExecInst;
    std::string m_Text;

};
typedef std::vector<NoMDEntries> NoMDEntriesSeq;

/*!
 * @brief This class represents the structure MarketDataIncrementalRefresh defined by the user in the IDL file.
 * @ingroup MarketDataIncrementalRefresh
 */
class MarketDataIncrementalRefresh
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport MarketDataIncrementalRefresh()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~MarketDataIncrementalRefresh()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object MarketDataIncrementalRefresh that will be copied.
     */
    eProsima_user_DllExport MarketDataIncrementalRefresh(
            const MarketDataIncrementalRefresh& x)
    {
                    m_header = x.m_header;

                    m_MDReqID = x.m_MDReqID;

                    m_c_NoMDEntries = x.m_c_NoMDEntries;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object MarketDataIncrementalRefresh that will be copied.
     */
    eProsima_user_DllExport MarketDataIncrementalRefresh(
            MarketDataIncrementalRefresh&& x) noexcept
    {
        m_header = std::move(x.m_header);
        m_MDReqID = std::move(x.m_MDReqID);
        m_c_NoMDEntries = std::move(x.m_c_NoMDEntries);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object MarketDataIncrementalRefresh that will be copied.
     */
    eProsima_user_DllExport MarketDataIncrementalRefresh& operator =(
            const MarketDataIncrementalRefresh& x)
    {

                    m_header = x.m_header;

                    m_MDReqID = x.m_MDReqID;

                    m_c_NoMDEntries = x.m_c_NoMDEntries;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object MarketDataIncrementalRefresh that will be copied.
     */
    eProsima_user_DllExport MarketDataIncrementalRefresh& operator =(
            MarketDataIncrementalRefresh&& x) noexcept
    {

        m_header = std::move(x.m_header);
        m_MDReqID = std::move(x.m_MDReqID);
        m_c_NoMDEntries = std::move(x.m_c_NoMDEntries);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x MarketDataIncrementalRefresh object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const MarketDataIncrementalRefresh& x) const
    {
        return (m_header == x.m_header &&
           m_MDReqID == x.m_MDReqID &&
           m_c_NoMDEntries == x.m_c_NoMDEntries);
    }

    /*!
     * @brief Comparison operator.
     * @param x MarketDataIncrementalRefresh object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const MarketDataIncrementalRefresh& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member header
     * @param _header New value to be copied in member header
     */
    eProsima_user_DllExport void header(
            const Header& _header)
    {
        m_header = _header;
    }

    /*!
     * @brief This function moves the value in member header
     * @param _header New value to be moved in member header
     */
    eProsima_user_DllExport void header(
            Header&& _header)
    {
        m_header = std::move(_header);
    }

    /*!
     * @brief This function returns a constant reference to member header
     * @return Constant reference to member header
     */
    eProsima_user_DllExport const Header& header() const
    {
        return m_header;
    }

    /*!
     * @brief This function returns a reference to member header
     * @return Reference to member header
     */
    eProsima_user_DllExport Header& header()
    {
        return m_header;
    }


    /*!
     * @brief This function copies the value in member MDReqID
     * @param _MDReqID New value to be copied in member MDReqID
     */
    eProsima_user_DllExport void MDReqID(
            const std::string& _MDReqID)
    {
        m_MDReqID = _MDReqID;
    }

    /*!
     * @brief This function moves the value in member MDReqID
     * @param _MDReqID New value to be moved in member MDReqID
     */
    eProsima_user_DllExport void MDReqID(
            std::string&& _MDReqID)
    {
        m_MDReqID = std::move(_MDReqID);
    }

    /*!
     * @brief This function returns a constant reference to member MDReqID
     * @return Constant reference to member MDReqID
     */
    eProsima_user_DllExport const std::string& MDReqID() const
    {
        return m_MDReqID;
    }

    /*!
     * @brief This function returns a reference to member MDReqID
     * @return Reference to member MDReqID
     */
    eProsima_user_DllExport std::string& MDReqID()
    {
        return m_MDReqID;
    }


    /*!
     * @brief This function copies the value in member c_NoMDEntries
     * @param _c_NoMDEntries New value to be copied in member c_NoMDEntries
     */
    eProsima_user_DllExport void c_NoMDEntries(
            const NoMDEntriesSeq& _c_NoMDEntries)
    {
        m_c_NoMDEntries = _c_NoMDEntries;
    }

    /*!
     * @brief This function moves the value in member c_NoMDEntries
     * @param _c_NoMDEntries New value to be moved in member c_NoMDEntries
     */
    eProsima_user_DllExport void c_NoMDEntries(
            NoMDEntriesSeq&& _c_NoMDEntries)
    {
        m_c_NoMDEntries = std::move(_c_NoMDEntries);
    }

    /*!
     * @brief This function returns a constant reference to member c_NoMDEntries
     * @return Constant reference to member c_NoMDEntries
     */
    eProsima_user_DllExport const NoMDEntriesSeq& c_NoMDEntries() const
    {
        return m_c_NoMDEntries;
    }

    /*!
     * @brief This function returns a reference to member c_NoMDEntries
     * @return Reference to member c_NoMDEntries
     */
    eProsima_user_DllExport NoMDEntriesSeq& c_NoMDEntries()
    {
        return m_c_NoMDEntries;
    }



private:

    Header m_header;
    std::string m_MDReqID;
    NoMDEntriesSeq m_c_NoMDEntries;

};

} // namespace MarketDataIncrementalRefresh

#endif // _FAST_DDS_GENERATED_MARKETDATAINCREMENTALREFRESH_MARKETDATAINCREMENTALREFRESH_HPP_


